# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.gettherisk <- function(parsonnetscore, coeff) {
    .Call(`_vlad_gettherisk`, parsonnetscore, coeff)
}

.optimal_k <- function(QA, df, coeff, yemp) {
    .Call(`_vlad_optimal_k`, QA, df, coeff, yemp)
}

.calceo <- function(df, coeff, yemp) {
    .Call(`_vlad_calceo`, df, coeff, yemp)
}

.eocusum_arl_sim <- function(r, k, h, df, coeff, yemp, side) {
    .Call(`_vlad_eocusum_arl_sim`, r, k, h, df, coeff, yemp, side)
}

.eocusum_arloc_sim <- function(r, k, h, df, coeff, coeff2, QS, side) {
    .Call(`_vlad_eocusum_arloc_sim`, r, k, h, df, coeff, coeff2, QS, side)
}

.eocusum_ad_sim <- function(r, k, h, df, coeff, coeff2, QS, side, type, m) {
    .Call(`_vlad_eocusum_ad_sim`, r, k, h, df, coeff, coeff2, QS, side, type, m)
}

.racusum_arl_mc <- function(pmix, RA, RQ, h, scaling, rounding, method) {
    .Call(`_vlad_racusum_arl_mc`, pmix, RA, RQ, h, scaling, rounding, method)
}

.racusum_crit_mc <- function(pmix, L0, RA, R, scaling, rounding, method, jmax, verbose) {
    .Call(`_vlad_racusum_crit_mc2`, pmix, L0, RA, R, scaling, rounding, method, jmax, verbose)
}

.llr_score <- function(df, coeff, R0, RA, yemp) {
    .Call(`_vlad_llr_score`, df, coeff, R0, RA, yemp)
}

.bcusum_arl_sim <- function(r, h, df, R0, RA) {
    .Call(`_vlad_bcusum_arl_sim`, r, h, df, R0, RA)
}

.racusum_arl_sim <- function(r, coeff, h, df, R0, RA, yemp) {
    .Call(`_vlad_racusum_arl_sim`, r, coeff, h, df, R0, RA, yemp)
}

.racusum_arloc_sim <- function(r, coeff, coeff2, h, df, R0, RA, RQ) {
    .Call(`_vlad_racusum_arloc_sim`, r, coeff, coeff2, h, df, R0, RA, RQ)
}

.racusum_adoc_sim <- function(r, coeff, coeff2, h, df, R0, RA, RQ, m, type) {
    .Call(`_vlad_racusum_adoc_sim`, r, coeff, coeff2, h, df, R0, RA, RQ, m, type)
}

