# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.gettherisk <- function(parsonnetscore, coeff) {
    .Call('_vlad_gettherisk', PACKAGE = 'vlad', parsonnetscore, coeff)
}

.optimal_k <- function(QA, parsonnetscores, coeff) {
    .Call('_vlad_optimal_k', PACKAGE = 'vlad', QA, parsonnetscores, coeff)
}

.calceo <- function(df, coeff, yemp = TRUE) {
    .Call('_vlad_calceo', PACKAGE = 'vlad', df, coeff, yemp)
}

.eocusum_arl_sim <- function(r, k, h, df, coeff, yemp = TRUE, side = 1L) {
    .Call('_vlad_eocusum_arl_sim', PACKAGE = 'vlad', r, k, h, df, coeff, yemp, side)
}

.eocusum_arloc_sim <- function(r, k, h, df, coeff, coeff2, QS = 1, side = 1L) {
    .Call('_vlad_eocusum_arloc_sim', PACKAGE = 'vlad', r, k, h, df, coeff, coeff2, QS, side)
}

.eocusum_adoc_sim <- function(r, k, h, df, coeff, coeff2, QS, side, type, m) {
    .Call('_vlad_eocusum_adoc_sim', PACKAGE = 'vlad', r, k, h, df, coeff, coeff2, QS, side, type, m)
}

.loglikelihood <- function(df, coeff, R0 = 1, RA = 2, yemp = TRUE) {
    .Call('_vlad_loglikelihood', PACKAGE = 'vlad', df, coeff, R0, RA, yemp)
}

.racusum_arl_nonRA <- function(r, h, df, R0 = 1, RA = 2) {
    .Call('_vlad_racusum_arl_nonRA', PACKAGE = 'vlad', r, h, df, R0, RA)
}

.racusum_arl_sim <- function(r, coeff, h, df, R0 = 1, RA = 2, yemp = TRUE) {
    .Call('_vlad_racusum_arl_sim', PACKAGE = 'vlad', r, coeff, h, df, R0, RA, yemp)
}

.racusum_arloc_sim <- function(r, coeff, coeff2, h, df, R0 = 1, RA = 2, RQ = 1) {
    .Call('_vlad_racusum_arloc_sim', PACKAGE = 'vlad', r, coeff, coeff2, h, df, R0, RA, RQ)
}

.racusum_adoc_sim <- function(r, coeff, coeff2, h, df, R0 = 1, RA = 2, RQ = 1, m = 5L) {
    .Call('_vlad_racusum_adoc_sim', PACKAGE = 'vlad', r, coeff, coeff2, h, df, R0, RA, RQ, m)
}

.racusum_adoc2_sim <- function(r, coeff, coeff2, h, df, R0 = 1, RA = 2, RQ = 1, m = 5L) {
    .Call('_vlad_racusum_adoc2_sim', PACKAGE = 'vlad', r, coeff, coeff2, h, df, R0, RA, RQ, m)
}

