# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.optimal_k <- function(pmix, RA, yemp) {
    .Call(`_vlad_optimal_k`, pmix, RA, yemp)
}

.eocusum_arl_sim <- function(r, pmix, k, h, RQ, yemp, side) {
    .Call(`_vlad_eocusum_arl_sim`, r, pmix, k, h, RQ, yemp, side)
}

.eocusum_ad_sim <- function(r, pmix, k, h, RQ, side, type, m) {
    .Call(`_vlad_eocusum_ad_sim`, r, pmix, k, h, RQ, side, type, m)
}

.FWT2 <- function(w, QA, g0, g1, shape1, shape2, QS) {
    .Call(`_vlad_FWT2`, w, QA, g0, g1, shape1, shape2, QS)
}

.racusum_beta_arl_mc <- function(h, QA, g0, g1, shape1, shape2, r, method, QS) {
    .Call(`_vlad_racusum_beta_arl_mc`, h, QA, g0, g1, shape1, shape2, r, method, QS)
}

.racusum_beta_crit_mc <- function(L0, QA, g0, g1, shape1, shape2, method, r, jmax, verbose, QS) {
    .Call(`_vlad_racusum_beta_crit_mc`, L0, QA, g0, g1, shape1, shape2, method, r, jmax, verbose, QS)
}

.racusum_beta_arl_sim <- function(r, shape1, shape2, coeff, h, RA, rs, RQ) {
    .Call(`_vlad_racusum_beta_arl_sim`, r, shape1, shape2, coeff, h, RA, rs, RQ)
}

.racusum_betabinomial_arl_sim <- function(r, shape1, shape2, coeff, h, RA, rs, RQ) {
    .Call(`_vlad_racusum_betabinomial_arl_sim`, r, shape1, shape2, coeff, h, RA, rs, RQ)
}

.racusum_arl_mc <- function(pmix, RA, RQ, h, scaling, rounding, method) {
    .Call(`_vlad_racusum_arl_mc`, pmix, RA, RQ, h, scaling, rounding, method)
}

.racusum_crit_mc <- function(pmix, L0, RA, R, scaling, rounding, method, jmax, verbose) {
    .Call(`_vlad_racusum_crit_mc`, pmix, L0, RA, R, scaling, rounding, method, jmax, verbose)
}

.llr_score <- function(df, coeff, R0, RA, yemp) {
    .Call(`_vlad_llr_score`, df, coeff, R0, RA, yemp)
}

.bcusum_arl_sim <- function(r, h, df, R0, RA) {
    .Call(`_vlad_bcusum_arl_sim`, r, h, df, R0, RA)
}

.racusum_ad_sim <- function(r, pmix, h, RA, RQ, m, type) {
    .Call(`_vlad_racusum_ad_sim`, r, pmix, h, RA, RQ, m, type)
}

.racusum_arl_sim <- function(r, pmix, h, RA, RQ, yemp) {
    .Call(`_vlad_racusum_arl_sim`, r, pmix, h, RA, RQ, yemp)
}

